3.11: фикс багов
frontend-park-mail-ru/2022_1_SamoeKrNaz pull request #15
Opened 2022-04-22 14:15 UTC by yalublukotikov

2022-04-25 14:23 UTC, Victorius19 approved these changes

2022-04-28 00:52 UTC, DPeshkoff requested changes

2022-04-28 00:52 UTC, DPeshkoff commented on .eslintrc.json
> +        "no-invalid-this": "off",
Почему?

2022-05-02 18:22 UTC, DPeshkoff approved these changes

2022-05-02 18:24 UTC, merged