Переписать проект на ts
frontend-park-mail-ru/2022_1_SamoeKrNaz pull request #17
Opened 2022-05-02 14:23 UTC by Victorius19

2022-05-02 18:20 UTC, DPeshkoff requested changes

2022-05-02 18:20 UTC, DPeshkoff commented on src/modules/router.ts
> +			event.path.map((el) => { // path существует в типе MouseEvent, а ts думает, что нет
напоминалка поменять

2022-05-02 18:20 UTC, DPeshkoff commented on src/modules/types.ts
> +}
это что-то страшное
может разнести технические поля вроде типов и поля нагрузки в разные интерфейсы?

2022-05-02 18:20 UTC, DPeshkoff commented on src/stores/boards.ts
> +		boards: Array<any>,
any не очень гуд

2022-05-02 18:20 UTC, DPeshkoff commented on src/test.d.ts
> +declare module '*';
ооо, тесты будут?)

2022-05-02 18:20 UTC, DPeshkoff commented on src/views/boardPage/boardPage.hbs
> +</div>
\n

2022-05-02 18:20 UTC, DPeshkoff commented on src/views/boardsPage/boardsPage.hbs
> +{{> containerDesk/containerDesk }}
\n

2022-05-02 18:20 UTC, DPeshkoff commented on src/views/loginPage/loginPage.ts
>  						password: document.getElementById('input_pass').value,
ошибки миграции

2022-05-02 18:20 UTC, DPeshkoff commented on src/views/notFoundPage/notFoundPage.hbs
> +{{> notFoundBlock/notFoundBlock }}
\n

2022-05-02 18:35 UTC, yalublukotikov approved these changes

2022-05-03 18:53 UTC, DPeshkoff approved these changes

2022-05-03 18:53 UTC, merged