Planexa 2 fix static server
frontend-park-mail-ru/2022_1_SamoeKrNaz pull request #2
Opened 2022-03-02 21:45 UTC by yalublukotikov

2022-03-06 13:18 UTC, DPeshkoff requested changes
Привет, поревьюил
Нужно использовать [модули] (https://learn.javascript.ru/modules)
Плюс советую использовать классы там, где подходит по логике

2022-03-06 13:18 UTC, DPeshkoff commented on src/js/func.js
> +const true_pass = '123456'
это кто такой?)

2022-03-06 13:18 UTC, DPeshkoff commented on src/js/func.js
> +    return false;
42 и 32 строчки - функция только false возвращает?

2022-03-06 13:18 UTC, DPeshkoff commented on src/js/func.js
> +}
\n

2022-03-06 13:18 UTC, DPeshkoff commented on src/js/loginPage.js
> +
страница - тоже компонент, просто содержащий другие компоненты
здесь тоже шаблонизатор нужен вместо этого кода

2022-03-06 13:18 UTC, DPeshkoff commented on src/js/login.js
> +        addError('Слишком короткий логин')
все сообщения и константы лучше вынести в constants

2022-03-06 13:18 UTC, DPeshkoff commented on src/login_js.html
> +    <script  src="components/button/button.js"></script>
а если компонентов будет миллион?

можно подгрузить один модуль и в сам js наимпортировать из других файликов, браузер сам сходит и разберется)

2022-03-06 13:18 UTC, DPeshkoff commented on src/login_js.html
> +</html>
\n

2022-03-06 13:18 UTC, DPeshkoff commented on src/login_js.html
> +<div class="container">
отступ бы и закрывающий тег на ту же строчку

2022-03-06 13:18 UTC, DPeshkoff commented on src/login.html
> +</html>
не забудьте потом удалить

2022-03-06 13:20 UTC, yalublukotikov commented on src/js/func.js
> +const true_pass = '123456'
было сделано для проверки успешной валидации))))

2022-03-07 13:07 UTC, DPeshkoff requested changes
Много лишних файликов(
\+ не забывай про `'use strict'` и `;`

2022-03-07 13:07 UTC, DPeshkoff commented on package.json
> +  "type": "module",
а зачем ему тип "модуль"?

2022-03-07 13:07 UTC, DPeshkoff commented on package.json
> +    "hbs": "^4.2.0"
hbs больше не используется, по-моему

2022-03-07 13:07 UTC, DPeshkoff commented on src/basePage/basePage.js
> +};
сейчас ок, но на РК никаких моков на фронте быть не должно, все по сети должно приходить с бэкенда

2022-03-07 13:07 UTC, DPeshkoff commented on src/basePage/basePage.js
> +}
\n

2022-03-07 13:07 UTC, DPeshkoff commented on src/base_js.html
> +</html>
\n

2022-03-07 13:07 UTC, DPeshkoff commented on src/components/activeTask/activeTask.handlebars
> +</div>
\n

2022-03-07 13:07 UTC, DPeshkoff commented on src/components/cap/cap.handlebars
> +            New desk
английский текст

2022-03-07 13:07 UTC, DPeshkoff commented on src/components/descp/descp.js
> +})();
тоже сгенерированный код

2022-03-07 13:07 UTC, DPeshkoff commented on src/components/desk/desk.handlebars
> +<div class="Desk">
давай с маленькой буквы классы называть)

2022-03-07 13:07 UTC, DPeshkoff commented on src/loginPage/loginPage.js
> +const container = document.getElementsByClassName('container')[0]
;

2022-03-07 13:07 UTC, DPeshkoff commented on src/loginPage/loginPage.js
> +form.onsubmit = validateLoginPage
;

2022-03-08 11:33 UTC, DPeshkoff requested changes
накидал правок
нужен JSDoc
и нужно снимать обработчики при уходе со страницы (по клику, перенаправление - в любом случае)

2022-03-08 11:33 UTC, DPeshkoff commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
Давай напишем скрипты и будем ими запускать проект

2022-03-08 11:33 UTC, DPeshkoff commented on server/server.js
> +server.listen(SERVER_PORT)
Всё ещё нету(

2022-03-08 11:33 UTC, DPeshkoff commented on src/basePage/basePage.handlebars
> +{{> rightMenu}}
\n

2022-03-08 11:33 UTC, DPeshkoff commented on src/basePage/basePage.js
> +import {Ajax} from "../modules/ajax.js";
''

2022-03-08 11:33 UTC, DPeshkoff commented on src/basePage/basePage.js
> +    const tasks = {
таски отсюда нужно убрать, на РК все должно приходить с бэка

2022-03-08 11:33 UTC, DPeshkoff commented on src/basePage/basePage.js
> +        document.getElementsByClassName("header")[0].classList.toggle("header_open");
''

2022-03-08 11:33 UTC, DPeshkoff commented on src/basePage/basePage.js
> +        document.getElementsByClassName("main__cap")[0].classList.toggle("active-close");
''

2022-03-08 11:33 UTC, DPeshkoff commented on src/basePage/basePage.js
> +    document.getElementsByClassName('toggle__block')[0].onclick = toggleMenu;
го addEventListener

2022-03-08 11:33 UTC, DPeshkoff commented on src/basePage/basePage.js
> +        const aj = new Ajax();
го экспортировать уже созданный класс Ajax? так можно)

2022-03-08 11:33 UTC, DPeshkoff commented on src/css/style.css
> +}
\n

2022-03-08 11:33 UTC, DPeshkoff commented on src/index.html
> +</html>
\n

2022-03-08 11:33 UTC, DPeshkoff commented on src/js/index.js
> +        href: '/sighup',
опечатка

2022-03-08 11:33 UTC, DPeshkoff commented on src/js/index.js
> +const domainSize = 27;
в константы

2022-03-08 11:33 UTC, DPeshkoff commented on src/js/index.js
> +import {addError} from "../modules/errors.js";
''

2022-03-08 11:33 UTC, DPeshkoff commented on src/loginPage/loginPage.js
> +    form.onsubmit = validateLoginPage;
го addEventListener

2022-03-08 11:33 UTC, DPeshkoff commented on src/modules/ajax.js
> +'use strict';
в классах строгий режим по умолчанию, в остальных файликах проверьте, чтобы был)

2022-03-08 11:33 UTC, DPeshkoff commented on src/modules/errors.js
> +    return false;
всегда возвращает false?

2022-03-08 11:33 UTC, DPeshkoff commented on src/modules/validation.js
> +            /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
Давайте пока из кода уберем, чтобы не было неиспользуемого

2022-03-08 11:33 UTC, DPeshkoff commented on src/modules/validation.js
> +    return false;
Тут тоже false

2022-03-08 11:33 UTC, DPeshkoff commented on src/signupPage/signupPage.js
> +    form.onsubmit = validateSignUpPage;
го addEventListener

2022-03-08 11:33 UTC, DPeshkoff commented on src/signupPage/signupPage.js
> +};
\n

2022-03-08 13:50 UTC, DPeshkoff commented on src/modules/ajax.js
> +'use strict';
```suggestion

```

2022-03-08 13:54 UTC, DPeshkoff commented on src/signupPage/signupPage.js
> +    input_pas.addEventListener('blur', deletePrompt);
а где ты снимаешь обработчики при смене страницы?

2022-03-08 14:32 UTC, DPeshkoff requested changes

2022-03-08 14:32 UTC, DPeshkoff commented on .eslintrc.json
> +        "max-len": [1, 500]
многовато как-то

2022-03-08 14:32 UTC, DPeshkoff commented on .github/workflows/main.yml
> +        run: npm install eslint --save-dev
можно его поставить сразу и добавить возможность прогонять локально

2022-03-08 14:32 UTC, DPeshkoff commented on .stylelintrc.json
> +}
\n

2022-03-08 14:32 UTC, DPeshkoff commented on package.json
> +    "buildHandleBars": "bash script.sh && npx eslint src/*/*.js && cd server && node server.js "
можно распилить
eslint можно в отдельный скрипт + у него есть режим автоисправления, можно вторым скриптом
start может запускать сервер без билда
в скриптах можно вызывать другие скрипты, если что

2022-03-08 14:32 UTC, DPeshkoff commented on src/basePage/basePage.js
> +		});
мне не нравится, что catch везде пустые

2022-03-08 17:45 UTC, Victorius19 approved these changes

2022-03-08 21:08 UTC, shevvvo approved these changes

2022-03-08 21:34 UTC, DPeshkoff requested changes

2022-03-08 21:34 UTC, DPeshkoff commented on src/basePage/basePage.js.save
> + */
кто такой

2022-03-09 06:05 UTC, DPeshkoff approved these changes

2022-03-09 06:05 UTC, merged