4.02: Ссылка для присоединения
frontend-park-mail-ru/2022_1_SamoeKrNaz pull request #20
Opened 2022-05-21 17:08 UTC by yalublukotikov

2022-05-22 16:50 UTC, DPeshkoff requested changes

2022-05-22 16:50 UTC, DPeshkoff commented on src/components/taskBlock/taskBlock.hbs
> +                <div class="taskBlock__content-dop-users">
кажется, что это все-таки date

2022-05-22 16:50 UTC, DPeshkoff commented on src/views/boardPage/boardPage.ts
> +		copyText.setSelectionRange(0, 99999);
магические 99999

2022-05-22 16:50 UTC, DPeshkoff commented on src/views/taskView/taskView.ts
> +		copyText.setSelectionRange(0, 99999);
Магические 99999

2022-05-22 17:37 UTC, Victorius19 requested changes

2022-05-22 17:37 UTC, Victorius19 commented on src/stores/board.ts
> +			window.history.pushState('', '', '/board/'+res.body.idb);
А где пробел между + и элементами строки? (:

2022-05-22 17:37 UTC, Victorius19 commented on src/stores/board.ts
> +			window.history.pushState('', '', '/board/'+res.body.IdB);
Опять пробел

2022-05-22 17:37 UTC, Victorius19 commented on src/stores/board.ts
> +		const copyText = document.getElementsByClassName('createModal__settings_input_link')[0] as HTMLInputElement;
Ну раз я решил душнить, то буду до конца. Так что предлагаю использовать querySelector вместо getElementsByClassName (Просто, чтобы хотя бы в новом коде, что мы пишем были только querySelector)

2022-05-22 17:37 UTC, Victorius19 commented on src/views/boardPage/boardPage.ts
> +		const icon = document.getElementsByClassName('createModal__settings_link_icon');
Опять querySelector (:

2022-05-22 17:37 UTC, Victorius19 commented on src/views/invitePage/invitePage.ts
> +		document.getElementsByClassName('container')[0].innerHTML += html;
Зачем сначала очищать все body, а затем добавлять в него блок, созданный ручками. Лучше же просто запихнуть div с классом container сразу в шаблон и просто заменить все эти 6 строк на одну

2022-05-22 17:37 UTC, Victorius19 commented on src/views/notFoundPage/notFoundPage.ts
>  		document.body.innerHTML = '';
Тут аналогичный вопрос про очистку body и дива с классом контейней

2022-05-24 20:04 UTC, Victorius19 approved these changes

2022-05-24 20:07 UTC, yalublukotikov commented on src/components/taskBlock/taskBlock.hbs
> +                <div class="taskBlock__content-dop-users">
это не users, тут по верстке надо date

2022-05-24 20:07 UTC, DPeshkoff commented on src/stores/board.ts
> +		copyText.setSelectionRange(0, 99999);
теперь тут
го в константу

2022-05-24 20:14 UTC, DPeshkoff approved these changes

2022-05-24 20:14 UTC, merged