Добавлены новые правила для линтера, переписан скрипт для комплияции hbs
frontend-park-mail-ru/2022_1_SamoeKrNaz pull request #5
Opened 2022-03-12 09:29 UTC by yalublukotikov

2022-03-16 17:48 UTC, DPeshkoff requested changes

2022-03-16 17:48 UTC, DPeshkoff commented on package.json
> +    "buildHandleBars": "bash buildHandlebars.sh.sh && npx eslint src/*/*.js && cd server && node server.js ",
.sh .sh?

2022-03-26 21:58 UTC, DPeshkoff approved these changes

2022-03-27 13:00 UTC, Victorius19 approved these changes

2022-03-29 17:17 UTC, merged