2.22: Реализация роутера
frontend-park-mail-ru/2022_1_SamoeKrNaz pull request #7
Opened 2022-03-23 19:11 UTC by yalublukotikov

2022-03-26 21:58 UTC, DPeshkoff requested changes

2022-03-26 21:58 UTC, DPeshkoff commented on src/constants/constants.js
> +	loginPage : '/login',
CI падает(

2022-03-26 21:58 UTC, DPeshkoff commented on src/js/index.js
> +
Очень страшная цепочка

2022-03-26 21:58 UTC, DPeshkoff commented on src/modules/router.js
> +		// зарегистрировал ли такой путь
А давай здесь автоматически снимать обработчики с прошлой страницы? Чтобы было удобно и красиво

2022-03-29 17:14 UTC, DPeshkoff approved these changes

2022-03-31 15:05 UTC, Victorius19 approved these changes

2022-03-31 17:38 UTC, shevvvo approved these changes

2022-04-02 18:43 UTC, merged