2.20: Добавить диспетчер для flux-архитектуры
frontend-park-mail-ru/2022_1_SamoeKrNaz pull request #8
Opened 2022-03-29 17:07 UTC by Victorius19

2022-03-29 17:16 UTC, DPeshkoff requested changes

2022-03-29 17:16 UTC, DPeshkoff commented on src/modules/dispatcher.js
> +		this._i = 0; // итератор для
для чего?)

2022-03-29 17:16 UTC, DPeshkoff commented on src/modules/dispatcher.js
> +	 * @return {int} id зарегистрированного события
мне кажется, что оно number

2022-03-29 17:23 UTC, Victorius19 commented on src/modules/dispatcher.js
> +		this._i = 0; // итератор для
Поправил: итератор для выдачи айдишников событиям

2022-03-29 18:13 UTC, DPeshkoff requested changes

2022-03-29 18:13 UTC, DPeshkoff commented on src/modules/dispatcher.js
> +		this._isWaiting = {}; // false - начало исполняться, true если ожидает исполнения
а давайте Map

2022-03-31 21:05 UTC, DPeshkoff approved these changes

2022-03-31 21:06 UTC, merged